---
title: "Proposal for Eurovision Data Visualization Report"
subtitle: "Federico Arboleda, Ryan Hu, Chandler Naylon, Aryan Poonacha"
format: html
editor: visual
---

```{r}
#| label: load-pkgs
#| message: false
#| warning: false

library(tidyverse)
eurovision <- read.csv("data/eurovision.csv")
```

# Dataset

Eurovision is an international public song performance competition between European countries. Each country submits a song that is to be performed live to a centralized committee that plays the song over a common broadcast, and each country then votes on the other countries' songs. As of 2022, at least 52 countries have participated at least once. The competition has cemented itself as a periodic staple for each country to present a culturally significant piece on an international stage.

The dataset consists of every song and contestant performed in Eurovision history, along with all the associated data - year, host city and country, points received, final rank, etc. It contains 2,005 observations and 18 variables. The accompanying eurovision-votes.csv maintains a tally of which countries voted for which other countries in each year of the contest.

We chose this dataset because it contains a substantial mix of both numerical and categorical variables with little missing data, giving us significant freedom to create different visualizations. We also liked that the data was arranged by year, dating back to the first Eurovision in 1956, which will allow us to visualize relationships over time. Finally, since America does not participate in Eurovision and consequently gives the competition minimal publicity, we are excited to educate our audience on a largely unfamiliar topic.

# Questions

The two questions we want to answer are:

1.  Is there a home country advantage in Eurovision?

2.  Does the order in which contestants perform affect their success?

# Analysis Plan

Our first question asks if contestants from the host country tend to perform better than foreign contestants. We will visualize this relationship (or lack thereof) by first creating a binary variable for each observation that indicates whether the contestant was competing in their home country (done by matching the host country and artist country variables and returning "true" if a match, and "false" if not). From there, we can use our first plot to look year-by-year to see whether a contestant from the host country won, or even facet by decade to look at whether home country advantage was more prevalent in certain eras than others. Furthermore, we can use total points or final rank for each contestant as a measure of success and compare the distributions of these metrics between host country participants and non-host country participants in our second plot.

Our second question looks at whether the order in which contestants perform has a relationship with their success in Eurovision. To do so, we plan on using the variables running order to represent the order in which they perform, year for a temporal visualization, and either total points or rank to represent how they perform in the competition. In addition, since there may be too many ranks to visualize concisely, we can bucket the ranks into broader categories, such as first 10, middle 10, and final 10. One plot can visualize the relationship between running order and total points over time while another plot can visualize the distribution of the running order of winners over each decade, using the binary winner variable to filter out the data and grouping the years by decade to prevent the plot from being too crowded.

We do not plan on merging any external data for either question.

# References

https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-05-17/readme.md
